name: e2e-workflow

on: 
  push:

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build native with Maven
      run: mvn -B package
      
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@master
      with:
    # Optional: do not specify to match Chrome's version
    chromedriver-version: '88.0.4324.96'
    - run: |
    export DISPLAY=:99
    chromedriver --url-base=/wd/hub &
    sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
